como organizar os diretórios para treinamento:
label (etiqueta) nome do diretório
não interessa para o computador o nome do arquivo... 


In [30]:
import cv2 
import os #
import numpy as np
import pickle 
from PIL import Image #pip install pillow

In [31]:
#open image dir
#.py na pasta raiz e imagens em uma pasta separada
#BASE_DIR = os.path.dirname(os.path.abspath(__file__))

#para os jupyer notebook - pasta que está o scripit
BASE_DIR = os.path.abspath('')

#whereve the .py is save find the location
#true for any system
image_dir = os.path.join(BASE_DIR, "images")

In [32]:
face_cascade = cv2.CascadeClassifier('opencv-files/haarcascade_frontalface_alt2.xml')
recognizer = cv2.face.LBPHFaceRecognizer_create()

In [33]:
current_id = 0
label_ids ={} #dictionary
y_label = []
x_train = []

com esse procedimento conseguimos fazer a lista das imagens para treinamento 
.replace(" ", "-") 
caso tenha algum diretorio: fulano de tal; a label: fulano-de-tal 
y_label.append(label) #some number
x_train.append(path) #verify this image, turn into NUMPY array, GRAY

para o treinamento > deixar apenas um rosto por imagem
desta forma o haar cascade só irá identificar um rosto 

In [34]:
for root, dirs, files in os.walk(image_dir):
    for file in files:
        if file.endswith("png") or file.endswith("jpg"):
            path = os.path.join(root,file)
            #label = os.path.basename(os.path.dirname(path)).replace(" ","-").lower()
            label = os.path.basename(root).replace(" ","-").lower()
            print(label,path)
            
            '''
            if label in label_ids:
                pass
            else:
                label_ids[label] = current_id
                current_id += 1
                
            id_ = label_ids[label]
            '''
            
            if not label in label_ids:
                label_ids[label] = current_id
                current_id +=1
            id_ = label_ids[label]
            
            #y_label.append(label) #some number
            #x_train.append(path) #verify this image, turn into NUMPY array, GRAY
               #por que não utilizar o openCV?
            pil_image = Image.open(path).convert("L") #grayscale
            size(550,550)
            final_image = pil-IMAGE.RESIZE(size.Image.ANTIALIAS)
            image_array = np.array(final_image,"uint8")
            print(image_array)            
            faces = face_cascade.detectMultiScale(image_array,scaleFactor = 1.5, minNeighbors = 5)
                
            for (x,y,w,h) in faces:
                roi = image_array[y:y+h,x:x+w]
                x_train.append(roi)
                y_label.append(id_)
                
print(label_ids)
#print(y_label)
#print(x_train)

fun /home/Mariana/Documentos/VC/images/fun/mustache.png
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
fun /home/Mariana/Documentos/VC/images/fun/glasses.png
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
emilia-clarke /home/Mariana/Documentos/VC/images/emilia-clarke/5.jpg
[[ 81  57  57 ... 157 157 157]
 [ 82  57  58 ... 157 157 157]
 [ 83  58  58 ... 158 158 159]
 ...
 [ 47  77  73 ... 138 138 138]
 [ 47  72  73 ... 138 138 138]
 [ 47  72  73 ... 138 138 138]]
emilia-clarke /home/Mariana/Documentos/VC/images/emilia-clarke/1.jpg
[[  0   0   0 ...   5   6   7]
 [  0   0   0 ...   6   7   8]
 [  0   0   0 ...   8   9  10]
 ...
 [ 32  24  19 ... 174 192 166]
 [ 33  25  20 ... 170 179 170]
 [ 33  25  19 ... 179 158 194]]
emilia-clarke /home/Mariana/Documentos/VC/images/emilia-clarke/3.jpg
[[244 244 244 ... 233 233 233]
 [244 244 244 ... 233 233 2

In [35]:
with open("labels.pickle","wb") as f:
    pickle.dump(label_ids, f)

In [38]:
recognizer.train(x_train,np.array(y_label))
recognizer.save("trainner.yml")